apiVersion: "acid.zalan.do/v1"
kind: "postgresql"
metadata:
  name: "acid-zarf-atlassian"
  namespace: "postgres-operator"
  labels:
    team: acid
spec:
  teamId: "acid"
  postgresql:
    version: "13"
  numberOfInstances: 3
  enableConnectionPooler: true
  volume:
    size: "2Gi"
  users:
    confluence: []
  databases:
    confluence: confluence
  enableLogicalBackup: true
  logicalBackupSchedule: "*/2 * * * *"
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: "1"
      memory: 2000Mi
